export const ADD_CITY = 'ADD_CITY';
export const CURRENT_CITY = 'CURRENT_CITY';
export const ADD_FIVE_FORECASTS = 'ADD_FIVE_FORECASTS';
export const DELETE_CURRENT_MAIN_FORECAST = 'DELETE_CURRENT_MAIN_FORECAST';
export const DELETE_FIVE_FORECASTS = 'DELETE_FIVE_FORECASTS';
